### ISSUE TITLE
templateUrl in sub-packages

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/angular-hbp-collaboratory#62]
In the sub-packages such as `ui-error`, the directives use partials/templates, such as `error-message.directive.html`, which are stored in the same directory as the javascript code, and the `templateUrl` attribute is just the filename, no path information.

However, Angular turns a `templateUrl` like `error-message.directive.html` into a path like `/error-message.directive.html`, i.e. it tries to serve it from the server root.

This is perhaps a dumb question, but how are we supposed to deploy `angular-hbp-collaboratory` so that the templates are found correctly?

**Comment by AFrancani** [comment]
`angular-hbp-collaboratory` uses [`gulp-angular-embed-templates`](https://github.com/mebyz/gulp-angular-embed-templates) in its build process. It replaces the template urls with the content of the template.

To deploy `angular-hbp-collaboratory`, just put its built `angular-hbp-collaboratory.js` file into your js folder and include it in your html files. Here is a minimum setup for an error message to be displayed:
``` HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>angular-hbp-collaboratory example app</title>
    <link rel="stylesheet" href="./bower_components/hbp-collaboratory-theme/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="./bower_components/angular-hbp-collaboratory/angular-hbp-collaboratory.css" />
  </head>

  <body ng-app="angular-hbp-collaboratory-example">
    <clb-error-message clb-error="{ message:'An error message!' }"></clb-error-message>

    <script src="./bower_components/angular/angular.js"></script>
    <script src="./bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="./bower_components/lodash/lodash.js"></script>
    <script src="./bower_components/hello/dist/hello.all.js"></script>
    <script src="./bower_components/angular-hbp-collaboratory/angular-hbp-collaboratory.js"></script>

    <script>
      angular.module('angular-hbp-collaboratory-example', ['clb-ui-error']);
    </script>

  </body>
</html>
```
